/**
 * Strategy engine types, schemas, and type guards.
 *
 * @see {@link ../../../adrs/0014-funding-rate-strategy.md ADR-0014: Funding Rate Prediction & Strategy}
 */

import * as v from "valibot";

// --- Type Aliases ---

/**
 * Funding rate trend direction.
 */
export type FundingRateTrend = "increasing" | "decreasing" | "stable";

/**
 * Funding rate regime classification.
 */
export type FundingRateRegime = "high_stable" | "high_volatile" | "low_stable" | "low_volatile";

/**
 * Source of funding rate data.
 */
export type FundingRateSource = "exchange" | "calculated";

/**
 * Signal confidence level.
 */
export type SignalConfidence = "HIGH" | "MEDIUM" | "LOW";

/**
 * Reason for exit signal.
 */
export type ExitReason = "rate_drop" | "trend_change" | "regime_change" | "target_reached" | "risk";

// --- Interfaces ---

/**
 * Snapshot of funding rate at a point in time.
 *
 * All prices in quote currency smallest units (`*Quote`),
 * rates in basis points (`*Bps`).
 */
export interface FundingRateSnapshot {
  symbol: string;
  currentRateBps: bigint;
  predictedRateBps: bigint;
  nextFundingTime: Date;
  lastFundingTime: Date;
  markPriceQuote: bigint;
  indexPriceQuote: bigint;
  timestamp: Date;
  source: FundingRateSource;
}

/**
 * Historical analysis of funding rate trends.
 */
export interface FundingRateHistory {
  snapshots: FundingRateSnapshot[];
  averageRateBps: bigint;
  volatilityBps: bigint;
  trend: FundingRateTrend;
  regime: FundingRateRegime;
}

/**
 * Strategy position with entry context for exit signal generation.
 */
export interface StrategyPosition {
  open: boolean;
  entryTime: Date;
  entryFundingRateBps: bigint;
  entryTrend: FundingRateTrend;
  entryRegime: FundingRateRegime;
  sizeQuote: bigint;
  side: "LONG" | "SHORT";
}

/**
 * Entry signal generated by strategy evaluation.
 */
export interface EntrySignal {
  type: "ENTER";
  confidence: SignalConfidence;
  reasons: string[];
  fundingRate: FundingRateSnapshot;
  history: FundingRateHistory;
  expectedYieldBps: bigint;
}

/**
 * Exit signal generated by strategy evaluation.
 */
export interface ExitSignal {
  type: "EXIT";
  reason: ExitReason;
  fundingRate: FundingRateSnapshot;
  history: FundingRateHistory;
  realizedYieldBps: bigint;
}

/**
 * Parameters for entering a hedge position.
 */
export interface EnterHedgeParams {
  sizeQuote: bigint;
  expectedYieldBps: bigint;
  confidence: SignalConfidence;
}

/**
 * Trading intent from strategy evaluation.
 */
export type TradingIntent =
  | { type: "NOOP" }
  | { type: "ENTER_HEDGE"; params: EnterHedgeParams }
  | { type: "EXIT_HEDGE"; reason: ExitReason | "risk" };

/**
 * Input for strategy evaluation (replaces nonexistent MarketState).
 */
export interface StrategyInput {
  fundingRate: FundingRateSnapshot;
  fundingHistory: FundingRateSnapshot[];
  position: StrategyPosition | null;
  equityQuote: bigint;
  marginUsedQuote: bigint;
}

// --- Valibot Schemas ---

export const fundingRateTrendSchema = v.picklist(["increasing", "decreasing", "stable"] as const);

export const fundingRateRegimeSchema = v.picklist([
  "high_stable",
  "high_volatile",
  "low_stable",
  "low_volatile",
] as const);

export const fundingRateSourceSchema = v.picklist(["exchange", "calculated"] as const);

export const signalConfidenceSchema = v.picklist(["HIGH", "MEDIUM", "LOW"] as const);

export const exitReasonSchema = v.picklist([
  "rate_drop",
  "trend_change",
  "regime_change",
  "target_reached",
  "risk",
] as const);

export const fundingRateSnapshotSchema = v.object({
  symbol: v.string(),
  currentRateBps: v.bigint(),
  predictedRateBps: v.bigint(),
  nextFundingTime: v.date(),
  lastFundingTime: v.date(),
  markPriceQuote: v.bigint(),
  indexPriceQuote: v.bigint(),
  timestamp: v.date(),
  source: fundingRateSourceSchema,
});

export const fundingRateHistorySchema = v.object({
  snapshots: v.array(fundingRateSnapshotSchema),
  averageRateBps: v.bigint(),
  volatilityBps: v.bigint(),
  trend: fundingRateTrendSchema,
  regime: fundingRateRegimeSchema,
});

export const strategyPositionSchema = v.object({
  open: v.boolean(),
  entryTime: v.date(),
  entryFundingRateBps: v.bigint(),
  entryTrend: fundingRateTrendSchema,
  entryRegime: fundingRateRegimeSchema,
  sizeQuote: v.bigint(),
  side: v.picklist(["LONG", "SHORT"] as const),
});

export const enterHedgeParamsSchema = v.object({
  sizeQuote: v.bigint(),
  expectedYieldBps: v.bigint(),
  confidence: signalConfidenceSchema,
});

export const entrySignalSchema = v.object({
  type: v.literal("ENTER"),
  confidence: signalConfidenceSchema,
  reasons: v.array(v.string()),
  fundingRate: fundingRateSnapshotSchema,
  history: fundingRateHistorySchema,
  expectedYieldBps: v.bigint(),
});

export const exitSignalSchema = v.object({
  type: v.literal("EXIT"),
  reason: exitReasonSchema,
  fundingRate: fundingRateSnapshotSchema,
  history: fundingRateHistorySchema,
  realizedYieldBps: v.bigint(),
});

export const tradingIntentSchema = v.union([
  v.object({ type: v.literal("NOOP") }),
  v.object({
    type: v.literal("ENTER_HEDGE"),
    params: enterHedgeParamsSchema,
  }),
  v.object({
    type: v.literal("EXIT_HEDGE"),
    reason: v.union([exitReasonSchema, v.literal("risk")]),
  }),
]);

export const strategyInputSchema = v.object({
  fundingRate: fundingRateSnapshotSchema,
  fundingHistory: v.array(fundingRateSnapshotSchema),
  position: v.nullable(strategyPositionSchema),
  equityQuote: v.bigint(),
  marginUsedQuote: v.bigint(),
});

// --- Type Guards ---

export const isFundingRateTrend = (value: unknown): value is FundingRateTrend =>
  v.is(fundingRateTrendSchema, value);

export const isFundingRateRegime = (value: unknown): value is FundingRateRegime =>
  v.is(fundingRateRegimeSchema, value);

export const isFundingRateSource = (value: unknown): value is FundingRateSource =>
  v.is(fundingRateSourceSchema, value);

export const isSignalConfidence = (value: unknown): value is SignalConfidence =>
  v.is(signalConfidenceSchema, value);

export const isExitReason = (value: unknown): value is ExitReason => v.is(exitReasonSchema, value);

export const isFundingRateSnapshot = (value: unknown): value is FundingRateSnapshot =>
  v.is(fundingRateSnapshotSchema, value);

export const isFundingRateHistory = (value: unknown): value is FundingRateHistory =>
  v.is(fundingRateHistorySchema, value);

export const isStrategyPosition = (value: unknown): value is StrategyPosition =>
  v.is(strategyPositionSchema, value);

export const isEnterHedgeParams = (value: unknown): value is EnterHedgeParams =>
  v.is(enterHedgeParamsSchema, value);

export const isEntrySignal = (value: unknown): value is EntrySignal =>
  v.is(entrySignalSchema, value);

export const isExitSignal = (value: unknown): value is ExitSignal => v.is(exitSignalSchema, value);

export const isTradingIntent = (value: unknown): value is TradingIntent =>
  v.is(tradingIntentSchema, value);

export const isStrategyInput = (value: unknown): value is StrategyInput =>
  v.is(strategyInputSchema, value);
