[build]
builder = "NIXPACKS"
buildCommand = "pnpm build"

[deploy]
preDeployCommand = ["pnpm db:migrate"]
startCommand = "pnpm start"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"